In [1]:
import numpy as np

In [2]:
def gen_MA_1(n, theta, ss): # ss = var of WN
    Lx = []
    wt = np.random.normal(0, ss**0.5, n)
    for t in range(1, n):
        xt = wt[t] + theta*wt[t-1]
        Lx.append(xt)
    return Lx

In [3]:
MD1_500, MD1_1000 = gen_MA_1(500, 5, 1), gen_MA_1(1000, 5, 1)

In [4]:
MD25_5000, MD25_1000 = gen_MA_1(500, 1/5, 25), gen_MA_1(1000, 1/5, 25) 

In [13]:
def Auto_cov_corr(D): # D = data
    Lcov = []
    x = D
    n = len(D)
    mu = np.mean(D)
    for h in range(0, 5):
        Lh = []
        for t in range(0, n-h):
            ac = (x[t+h]-mu) * (x[t]-mu)
            Lh.append(ac)
        auto_cov_h = sum(Lh) / n
        Lcov.append(auto_cov_h)
    AutoCov = np.array(Lcov)
    Sacf = AutoCov / AutoCov[0]
    print(AutoCov)
    print(Sacf)

In [14]:
Auto_cov_corr(MD1_500)

[26.38558301  4.26414942 -0.59006678  1.70420159 -1.11059455]
[ 1.          0.16160907 -0.02236323  0.06458836 -0.04209096]


In [15]:
Auto_cov_corr(MD1_1000)

[24.80194229  5.46072333  0.3096251  -0.27999113 -0.5545672 ]
[ 1.          0.22017321  0.01248391 -0.01128908 -0.02235983]
